name = "guildcertifiedv1-1"
compatibility_date = "2023-12-01"

[site]
bucket = "./"

[[rules]]
type = "Text"
globs = ["**/*.js"]
[rules.headers]
"Content-Type" = "application/javascript"

[[rules]]
type = "Text" 
globs = ["**/*.css"]
[rules.headers]
"Content-Type" = "text/css"
